= CN5121_GoT_Genealogy

== Setup

IMPORTANT: Must use Java 1.8, otherwise the JavaFX 8 GUI won't work as expected

* Install Java 1.8 JDK
* Install Git
* Install Maven 4.0.0
* Import `pom.xml` into your IDE
* `(Optional)` Configure IDE to run with Maven attributes, using the `got-genealogy` working directory:
** `mvn clean install` - compile
** `mvn exec:java` - build

=== Maven on Windows

* Download `Binary zip archive`
* Unpack into a directory, e.g. `C:\Program Files\Apache Software Foundation\apache-maven-3.6.0`
* Add `bin` folder into PATH

== Compiling and Building

To compile the Java source code, go to `got-genealogy` and run:
[source, shell]
----
mvn clean install
----

Currently, there are no modules, so building is done by:

[source, shell]
----
mvn exec:java
----

== Debugging

IMPORTANT: You can also debug directly from the IDE.

To use with a debugger, you have to build the code with `mvnDebug` and connect to it remotely (default port: `8000`) from your IDE:

[source, shell]
----
mvnDebug exec:java
----

Compile and build shorthand:

[source, shell]
----
mvn clean install && mvnDebug exec:java
----

== Rights to media
icon.png - Application icon
https://commons.wikimedia.org/wiki/File:Game_of_Thrones_triple_slash_O.svg 

MainTheme.mp3 - Background Music
Ice and Fire - Ross Bugden 
https://www.youtube.com/watch?v=kthxycmF25M 

All other elements were created originally by memebrs of the group or edited by members of the group from content under no attribution license.
