package com.got.genealogy.core.family.person;

public enum Relationship {
    ASCENDANT_COUSIN,
    AUNT_OR_UNCLE,
    CHILD,
    COUSIN,
    DESCENDANT_COUSIN,
    GRANDAUNT_OR_UNCLE,
    GRANDCHILD,
    GRANDNIECE_OR_NEPHEW,
    GRANDPARENT,
    GREAT_GRANDAUNT_OR_UNCLE,
    GREAT_GRANDCHILD,
    GREAT_GRANDNIECE_OR_NEPHEW,
    GREAT_GRANDPARENT,
    HALF_SIBLING,
    NIECE_OR_NEPHEW,
    PARENT,
    SIBLING,
    SPOUSE,
    STEP_CHILD,
    STEP_PARENT
}

